# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app

# Qt modules
qtHaveModule(webview) {
    QT += core network widgets xml qml webengine quick
}

DEFINES += QT_NO_ICU

NOISE_C_DIR = $$PWD/../third_party/noise-c

# noise-c integration for the localhost policy transport.
DEFINES += ED25519_CUSTOMHASH ED25519_CUSTOMRANDOM

INCLUDEPATH += $$NOISE_C_DIR/include \
               $$NOISE_C_DIR/src \
               $$NOISE_C_DIR/src/protocol \
               $$NOISE_C_DIR/src/keys

QMAKE_CFLAGS += -Wno-expansion-to-defined

SOURCES += \
    $$NOISE_C_DIR/src/backend/ref/cipher-aesgcm.c \
    $$NOISE_C_DIR/src/backend/ref/cipher-chachapoly.c \
    $$NOISE_C_DIR/src/backend/ref/dh-curve25519.c \
    $$NOISE_C_DIR/src/backend/ref/hash-blake2b.c \
    $$NOISE_C_DIR/src/backend/ref/hash-blake2s.c \
    $$NOISE_C_DIR/src/backend/ref/sign-ed25519.c \
    $$NOISE_C_DIR/src/backend/ref/hash-sha256.c \
    $$NOISE_C_DIR/src/backend/ref/hash-sha512.c \
    $$NOISE_C_DIR/src/crypto/aes/rijndael-alg-fst.c \
    $$NOISE_C_DIR/src/crypto/blake2/blake2b.c \
    $$NOISE_C_DIR/src/crypto/blake2/blake2s.c \
    $$NOISE_C_DIR/src/crypto/chacha/chacha.c \
    $$NOISE_C_DIR/src/crypto/donna/poly1305-donna.c \
    $$NOISE_C_DIR/src/crypto/ed25519/ed25519.c \
    $$NOISE_C_DIR/src/crypto/ghash/ghash.c \
    $$NOISE_C_DIR/src/crypto/sha2/sha256.c \
    $$NOISE_C_DIR/src/crypto/sha2/sha512.c \
    $$NOISE_C_DIR/src/protocol/cipherstate.c \
    $$NOISE_C_DIR/src/protocol/dhstate.c \
    $$NOISE_C_DIR/src/protocol/errors.c \
    $$NOISE_C_DIR/src/protocol/handshakestate.c \
    $$NOISE_C_DIR/src/protocol/hashstate.c \
    $$NOISE_C_DIR/src/protocol/internal.c \
    $$NOISE_C_DIR/src/protocol/names.c \
    $$NOISE_C_DIR/src/protocol/patterns.c \
    $$NOISE_C_DIR/src/protocol/rand_os.c \
    $$NOISE_C_DIR/src/protocol/randstate.c \
    $$NOISE_C_DIR/src/protocol/signstate.c \
    $$NOISE_C_DIR/src/protocol/symmetricstate.c \
    $$NOISE_C_DIR/src/protocol/util.c



# Common Include Paths
INCLUDEPATH += $$OUT_PWD/GeneratedFiles \
               $$PWD/abstractions \
               $$PWD/components \
               $$PWD/../common \
               ../../tools/quazip-0.7.1/quazip

# Common Directories for Generated Files
UI_DIR += $$OUT_PWD/GeneratedFiles
RCC_DIR += $$OUT_PWD/GeneratedFiles
MOC_DIR += $$OUT_PWD/GeneratedFiles

# Object and Output Directory Configuration
CONFIG(release, debug|release) {
    OBJECTS_DIR += $$OUT_PWD/release
    DESTDIR = $$OUT_PWD/release
} else {
    OBJECTS_DIR += $$OUT_PWD/debug
    DESTDIR = $$OUT_PWD/debug
}

# Platform-specific Configuration
win32 {
    message("Configuring for Windows")

    # Build Options
    CONFIG += MAKE_FOR_VISTA
    DEFINES += STRSAFE_NO_DEPRECATE
    DEFINES += Q_OS_REDHAT=0 Q_OS_UBUNTU=0

    # Target and Libraries
    MAKE_FOR_VISTA {
        LIBS += -lMultipleMonitors
        TARGET = EDCClient
        CONFIG += warn_off
    }

    DEFINES += WINDOWS_OS \
               MAIN_UI_IME_DISABLE \
               MS_SERVICE_CODE \
               Q_OS_WIN_NONSTL

    LIBS += -L"$$PWD/../lib" -lquazip \
            -lws2_32 -lIphlpapi -lole32 -luuid -lu2ec -loleaut32 -lpsapi -lCrypt32

    RC_FILE = "edcui.rc"

    # Compiler Flags
    QMAKE_CXXFLAGS += -Wno-deprecated-writable-strings -O2
}

macx {
    message("Configuring for macOS")
    # Detect macOS version
    MACOS_VERSION = $$system(sw_vers -productVersion)
    MACOS_MAJOR_VERSION = $$replace(MACOS_VERSION, "\\..*", "")
    MACOS_MINOR_VERSION = $$replace(MACOS_VERSION, "^\\d+\\.(\\d+).*", "\\1")
    DEFINES += Q_OS_REDHAT=0 Q_OS_UBUNTU=0

    message("macOS version detected - EDCUI: $$MACOS_VERSION")

    # If macOS version is 14.x (Sonoma) or higher, use macosx14.2 SDK 
    #  greaterThan(MACOS_MAJOR_VERSION, 13) { 
    #      message("macOS 14.x or above detected. Using SDK macosx14.2.")
        
        QMAKE_MAC_SDK = macosx14.2

    #   } else {
    #      message("Using default macOS SDK.")
    #     QMAKE_MAC_SDK = macosx13.1 #ENABLE ON BHARAT MAC
    #  }


    QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.15

    TARGET = HyWorks
    CONFIG += warn_off

    LIBS += -L"$$PWD/../maclib" -lquazip

    # Architecture & optimization
    QMAKE_CXXFLAGS += -arch x86_64 -std=c++17
    QMAKE_CFLAGS += -arch x86_64
    QMAKE_LFLAGS += -arch x86_64

    QMAKE_CFLAGS_WARN_ON -= -Wall
    QMAKE_CXXFLAGS_WARN_ON -= -Wall

    # Required frameworks
    QMAKE_LFLAGS += \
        -framework Foundation \
        -framework AppKit \
        -framework SwiftUI

    # Link to Swift dylib
    LIBS += -L$$PWD -lAppControlSw
}

linux {
    message("Configuring for Linux")

    TARGET = edcuibin

    # RPATH and Gold Linker Configuration
    QMAKE_LFLAGS += -Wl,--rpath=\\\$\$ORIGIN \
                    -Wl,--rpath=\\\$\$ORIGIN/qt_dep/lib \
                    -Wl,--rpath=\\\$\$ORIGIN/libs \
                    -fuse-ld=gold

    CONFIG(debug, debug|release) {
        DEFINES += DEBUG
    }


    # Check if running on RedHat (RHEL)
    OS_CHECK = $$system(cat /etc/os-release | grep -E 'rhel' >/dev/null && echo 1 || echo 0)

    # Debug output
    message("OS_CHECK = $$OS_CHECK")

    # Set the appropriate defines based on the OS detection
    contains(OS_CHECK, 1) {
        message("Detected: RedHat (RHEL)")
        DEFINES += Q_OS_REDHAT=1 Q_OS_UBUNTU=0
    } else {
        message("Detected: Ubuntu or other OS")
        DEFINES += Q_OS_REDHAT=0 Q_OS_UBUNTU=1
    }

    # Final output for debugging
    message("Final DEFINES = $$DEFINES")


    INCLUDEPATH += /usr/include/openssl
    message("Final INCLUDEPATH = $$INCLUDEPATH")

    LIBS += -L"$$PWD/../lib_x64" -lX11 -lquazip -ltpif -lrt -lssl -lcrypto -lsystemd

    contains(QT_ARCH, i386) {
        message("Linux 32-bit")
        LIBS += -L"$$PWD/../lib_x86"
    } else {
        message("Linux 64-bit")
    }
}

# Include the Project File
include(edcui.pri)
